# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: weather-api
        image: your-dockerhub-username/weather-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: db-storage
          mountPath: /app/instance
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: weather-api-pvc

---
# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  type: NodePort
  selector:
    app: weather-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000

---
# k8s/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi