name: CI Pipeline

on:
  push:
    branches: [ testing ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pytest tests/ -v

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      if: success()  # Only run if tests pass
      with:
        push: false  # Set to true when you have Docker Hub credentials
        tags: weather-api:latest